[package]
name = "whereto"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
reqwest = "0.11"
serde_json = "1.0"
structopt = "0.3"
tabular = "0.1"
tokio = { version = "1", features = ["full", "rt"] }
